# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170809_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
